### PR TITLE
Windows phone contact picker filter

### PR DESCRIPTION
**Pull request by Hurtyto**
Added textbox to filter contacts in the contact picker for Windows Phone

### CODE REVIEW

**Comment by purplecabbage** [comment]
Hi @Hurtyto 
This looks good. Have you signed the CLA?
I cannot find your github username, or parts of your email address listed on https://people.apache.org/committer-index.html
Note, It would also be helpful if you could add your name to your github profile

More info on contributing here: http://cordova.apache.org/#contribute

**Comment by Hurtyto** [comment]
Haven't signed yet. When I get some time will do, but feel free to use my contribution if needed

**Comment by purplecabbage** [comment]
Yeah, we can't accept the code without a signed CLA on file. It'll wait.

**Comment by Hurtyto** [comment]
Sure. I will sign it as soon as possible then :)

-----Original Message-----

**Comment by purplecabbage** [comment]
Hey @Hurtyto 
Any update on this?

**Comment by Hurtyto** [comment]
Still haven't. Couldn't find much time :( I hope that will do it soon.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-contacts/pull/51/commits/ecea5fe0ed9575b0b9dd6b25438a2452ae6c4ef9)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/10//label=mac-slave,platformName=android/artifact/) |

**Comment by cordova-qa** [comment]
Can one of the admins verify this patch?

**Comment by filmaj** [comment]
Until @Hurtyto signs the ICLA, we cannot accept this patch :(

**Comment by Hurtyto** [comment]
Just accept it. No need to sign.

**Comment by maverickmishra** [comment]
This plugin is being deprecated. No more work will be done on this plugin by the Cordova development community. You can continue to use this plugin and it should work as-is in the future but any more arising issues will not be fixed by the Cordova community.

**Comment by purplecabbage** [comment]
... not to mention the fact we don't support Windows Phone either ..

**Pull request closed without merging**
