### PR TITLE
Solved problem add Contact photos from relative and absolute path for Android: Get input stream from relative and full path in ContactAccessorSdk.java

### PR DESCRIPTION
**Pull request by vincipop**
"Get an input stream based on file path or uri "  didn't work for relative paths and full paths (file:///) so modified the "getPathFromUri" method

### CODE REVIEW

**Comment by vladimir-kotikov** [comment]
Hi @vincipop, before merging could you please sign the Apache CLA? Also it would be great if you filed an issue in [JIRA](https://issues.apache.org/jira/issues/?jql=project%20%3D%20CB)

More info on contributing here: http://cordova.apache.org/contribute/

**Comment by vincipop** [comment]
Hi @vladimir-kotikov , 
Apache CLA signed
Issue filed on JRA : https://issues.apache.org/jira/browse/CB-10039
Thanks

**Comment by vladimir-kotikov** [comment]
@vincipop, looks like your changes does not handle the case, when image path is an absolute path to file outside of assets/storage directory (`/res/images/some_file.jpg` or `file:///res/images/some_file.jpg`).

Could you please try out #94 and let me know if it works for you.

**Comment by vincipop** [comment]
@vladimir-kotikov, I tried out #94 and it works for me. 
Perfect,  thanks !

**Pull request closed without merging**
