### PR TITLE
Remove logging

### PR DESCRIPTION
**Pull request by omefire**

### CODE REVIEW

**Comment by omefire** [comment]
@sarangan12 could you please review this ?

**Comment by sarangan12** [comment]
@omefire why are you removing this? This was actually pretty useful in debugging

**Comment by sarangan12** [comment]
@omefire I am ok with removing the logging. Please check the travis erros.

**Comment by omefire** [comment]
@sarangan12 errors fixed.

**Comment by sarangan12** [comment]
Lgtm

**Pull request closed without merging**
