### PR TITLE
CB-9078 Android - Filter search: hasPhoneNumber

### PR DESCRIPTION
**Pull request by jonmikelm**
When searching for all the contacts in Android, by default all the google contacts(Gmail history, etc...) are returned. This causes performance problems when the number of contacts is big.

Usually, we only want contacts that have a phone number informed. I have addes a new optional boolean parameter to the options object of the "find" method: "phoneNumberInformedOnly"

If we send true in this parameter, the where clause of the select to the contacts database will include:
      
      "AND (" + ContactsContract.Contacts.HAS_PHONE_NUMBER + " = 1)"
      
This filter is also added if a filter string is sent to the search method.

Use case:

    // find all contacts with 'Bob' in any name field
    var options      = new ContactFindOptions();
    options.multiple = true;
    options.phoneNumberInformedOnly = true;
    options.desiredFields = [navigator.contacts.fieldType.id];
    var fields       = [navigator.contacts.fieldType.displayName, navigator.contacts.fieldType.name];
    navigator.contacts.find(fields, onSuccess, onError, options);

### CODE REVIEW

**Comment by purplecabbage** [comment]
Can we make the option param name simply 'hasPhoneNumber'?

**Comment by purplecabbage** [comment]
Please document the new param and create a JIRA ticket also. This should potentially be done on other platforms also.

**Comment by jonmikelm** [comment]
I changed the param name and readme file. I have also opened a JIRA but I'm not sure if I've filled the form correctly. It's the first I open...

https://issues.apache.org/jira/browse/CB-9078

**Comment by jason-engage** [comment]
Will this pull request make it into the master soon? I would like to use it asap.

**Comment by jonmikelm** [comment]
We are already using this code in a public app and we would be pleased if this changes were merged to  the master branch.

I have changed the pull request name to include the JIRA code, and I have updated the fork to the latest master commit. 

Is there any other step we could take to make this process faster?

**Pull request closed without merging**
