### PR TITLE
(android) Fix issue crash on save and remove method

### PR DESCRIPTION
**Pull request by igormartsekha**
### Platforms affected
Android

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by janpio** [comment]
Can you please explain the changes you did and why those are required? Otherwise it will be hard to review your PR and merge it.

**Comment by igormartsekha** [comment]
@janpio Hello
if someone wants to use remove and save method, them should receive WRITE and READ permissions to do it. Current version asks WRITE permission for save() and remove() method but doesn't ask READ permission. If you run save/remove without READ permission, a app will throw the exception and crashed.
So, my changes will fix this behaviour and save/remove methods will work in proper way.

**Comment by oscardavidiaz** [comment]
Hello, pleease install the android API level 27 that corresponds to Android 8.1(Oreo) before execute The Travis CI build.

**Comment by juanludukeboss** [comment]
Hi, I have Android 10 and API Level 27 and I have made the changes indicated in the commit: https://github.com/apache/cordova-plugin-contacts/pull/221/commits/d6f42ebfcb8b9db43204c5df03d8d98f385aedfe , but when I try to save the contact, the App Crash. The contact is saved perfectly, but the App Crash. 
I have tested always in Android 9 and I have the same problem.

Any idea??. Please, I need a solution.

Thank so much.

**Comment by juanludukeboss** [comment]
Sorry, Finally it's working Perfectly. My problem was that I had not removed the android platform and added again.
Thanks so much, I'm very happy that my problem with the save contacts is solved.
👍 👍

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.

**Pull request closed without merging**
