### PR TITLE
Remove ops

### PR DESCRIPTION
**Pull request by manugb**
I made an isolate project that only handles this plugin.
And when I modify an existing contact and print the rows of cursor in line 272
I got like 1000 more rows.
I keept running this sequence over and over and everytime the rows count got bigger and bigger
So when I start analyzing the modify contact method I foung this ops to be the source of the bug.
I comment it and run the sequence again and the row count didnt increase.

What do you think ?

### CODE REVIEW

**Comment by manugb** [comment]
Had anyone take a look at this ?

**Comment by manugb** [comment]
Someone please

**Comment by purplecabbage** [comment]
Commenting out code is never the solution.
This file appears to desperately need a refactor anyway.  
I don't know enough about the android native api to commit this change.  Maybe @infil00p or @csantanapr could have a look.

**Comment by manugb** [comment]
I dont know enough android either to fix it, all I know is that the op I comment out is the one making trouble.

I think that the ops means to do an update into the whole ContractData.RawContacts table, if its doing that, the query makes no sense.

**Comment by manugb** [comment]
The idea is for someone who has more knowledge of android to erase this op along with the comment and merge it

**Comment by csantanapr** [comment]
I'm not android SME, maybe @macdonst can take a look.

My general comment on this PR, is that if you don't know what are not sure what's the root cause of the problem, and and not sure about a proper fix you should not submit a patch, maybe better to open a new issue in JIRA http://issues.cordova.io with all background info you found so far.

PS: Android can be a mess to support, just because something work in one version of Android doesn't mean that will work the same way in all other versions of Android.

**Comment by infil00p** [comment]
Is there a JIRA issue related to this pull request.  We need to be able to see what the problem is before we can talk about this issue.  We're not going to accept a pull request where you comment code out, especially since git is version control and we can just delete it anyway.

**Comment by manugb** [comment]
Can you guys create an issue on your Jira with this info so we close this PR.
Because is actually a MAJOR issue

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-contacts/pull/70/commits/1d923b372f1ad92871e3b8bc3398af454162eba1)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-contacts-pr/9//label=mac-slave,platformName=android/artifact/) |

**Comment by cordova-qa** [comment]
Can one of the admins verify this patch?

**Comment by filmaj** [comment]
As discussed, the issue in question should be discussed and a problem identified first before a solution is proposed.

If this is still a problem, please head over to https://issues.apache.org/jira/browse/CB, sign up and file an issue with the relevant problem details. We can go from there.

Closing this PR.

**Pull request closed without merging**
