### PR TITLE
Return rawId

### PR DESCRIPTION
**Pull request by manugb**
contactAccessor.getContactById() actually expects the contact rawId

### CODE REVIEW

**Comment by manugb** [comment]
Had anyone take a look at this ?

**Comment by purplecabbage** [comment]
Hey @manugb 
Sorry for the delay in looking at this. Can you point to where it says rawId should be returned, or explain why?  Looking at the code, it is very hard to tell, but it seems create is returning an id, and not a rawId, and save is calling either create||modify so it seems they should both return the same type of id.

Also, it would be great if we could have a test added that proves this error exists, and also that this pr fixes it.

**Comment by manugb** [comment]
Hi @purplecabbage 
Im sorry but I dont have time right now to write a test suite. Anyway here is the description

It was happening to me that when I was updating a contact, the contact was getting updated successfully BUT I got the error callback executed. 
This seemed wierd to me so I dig in the [modifyContact](https://github.com/apache/cordova-plugin-contacts/blob/master/src/android/ContactAccessorSdk5.java#L1015) method and find out that was returning the contactID but the [getContactByID](https://github.com/apache/cordova-plugin-contacts/blob/master/src/android/ContactAccessorSdk5.java#L302) methods used [here](https://github.com/apache/cordova-plugin-contacts/blob/master/src/android/ContactManager.java#L106) is expecting the RAW contactId, therefore I make the change and then I could successfully update the contact and get the success callback executed

The test should be something like:
* get an existing contact
* modify it and save it
* check that the error callback was called
* check that the contact was modified correctly despite error callack being called

update modifyContact to return RawID
* same as before but check success cb is executed

**Comment by vladimir-kotikov** [comment]
@manugb, this was fixed in #87, please close this PR

**Pull request closed without merging**
