### PR TITLE
(ios) fixes background thread problem in pickContact method

### LINKED ISSUE #228: App Crash with iOS 14
# Bug Report

## Problem
The app crashes after the permissions window appears and you click "allow." If you re-open the app, the permission is granted and you can access the contacts correctly. Has anyone else seen this or know any fixes/forks that address this?

### What is expected to happen?
The app will not crash after allowing contact permissions.

### What does actually happen?
It crashes.

## Information

I have set the NSContactsUsageDescription in Info.plist and see that when it prompts so I know that isn't the problem. From debugging the crash log there is an error that says: 
`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Call must be made on main thread'`

I suspect this is a problem with the way the plugin is implemented not using the main thread 

### Command or Code

The `pickContact` method being called for the first time in an app, causing the permissions window to appear. After accepting you should see the crash.

### Environment, Platform, Device

All iOS devices on version 14 (could have been happening earlier but I didn't notice it).

### Version information

Cordova 10, cordova-plugin-contacts 3.0.1 (latest)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

### PR DESCRIPTION
**Pull request by lukas2**
This fixes  #228

### CODE REVIEW

**Review by breautek — APPROVED** [review]

**Comment by Sampath-Lokuge** [comment]
Can we have the new version with this fix?

**Comment by breautek** [comment]
> Can we have the new version with this fix?

Before we can merge or make a release, the plugin needs to have it's testing tools updated. The tests are failing because it's still using versions that are no longer supported. To get this PR merged, I'd also like at least one other PMC member to vote green.

For the record, I don't believe anything in this change is causing the test to fail, just travis and appveyor configs needs to be updated. I have some time, I'll make those changes now. Once the test changes are merged in, I'll restart the checks here, and if they turn green I'll start nudging people to take a look.

**Comment by Sampath-Lokuge** [comment]
@breautek Ok sure. Thanks!

**Comment by breautek** [comment]
Actually there won't be any releases (and I'll probably won't convince anybody else for a green check) as this plugin is deprecated. My apologies, I didn't realise this plugin was deprecated initially.

See https://github.com/apache/cordova-plugin-contacts#deprecation-notice and https://cordova.apache.org/news/2017/11/27/Deprecation-of-cordova-contacts-plugin.html for more details.

I personally don't know of any migration strategy or alternate solution, feel free to use your own fork of this plugin.

**Comment by Sampath-Lokuge** [comment]
@breautek Yes, I have manually applied this fix https://github.com/apache/cordova-plugin-contacts/pull/229/commits/868cfba60d2328306e3bb13bf98643c08c501622 on this plugin and it works. I use `2.3.1` Thanks!

**Comment by zimejin** [comment]
> @breautek Yes, I have manually applied this fix [868cfba](https://github.com/apache/cordova-plugin-contacts/commit/868cfba60d2328306e3bb13bf98643c08c501622) on this plugin and it works. I use `2.3.1` Thanks!

Hi, I'm experiencing this issue as well. How do I apply the fix to my project? Thanks.

**Comment by Sampath-Lokuge** [comment]
@zimejin You need to add this fix https://github.com/apache/cordova-plugin-contacts/pull/229/commits/868cfba60d2328306e3bb13bf98643c08c501622 to here `src/ios/CDVContacts.m`

**Comment by zimejin** [comment]
@Sampath-Lokuge Thanks for the quick response. I'll give this a try.  

Regards

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.

**Pull request closed without merging**
