### PR TITLE
Fix for CB-4614

### PR DESCRIPTION
**Pull request by svkirans**
Fix for CB-4614

### CODE REVIEW

**Comment by jsoref** [comment]
Please see http://wiki.apache.org/cordova/IssueWorkflow#About_Commit_Messages

**Comment by svkirans** [comment]
Added documentation for remove and save functions in contact.

**Comment by jsoref** [comment]
@svkirans: please use `git commit --amend` and fix your commit message to match the style.

**Comment by svkirans** [comment]
@jsoref 
Changed the styling and sent an updated pull request.

**Comment by jsoref** [comment]
The first line of your commit message isn't in the right form.

Also, please use `git rebase -i` and you should `fold` your commits into a single commit.

**Pull request closed without merging**
